import { user2 } from "@/assets/images";
import {  Profile } from "@/types/types";

  export const profiles: Profile[] = [
    {
      id: 1,
      image: user2.src,
      name: "Davina",
      age: 23,
      location: "Abuja",
      matchPercentage: 85,
      verified: true,
      bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec.",
      liked: false,
    },
    {
      id: 2,
      image: user2.src,
      name: "Emily",
      age: 31,
      location: "Lagos",
      matchPercentage: 80,
      verified: false,
      bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec.",
      liked: false,
    },
    {
      id: 3,
      image: user2.src,
      name: "John",
      age: 28,
      location: "Delta",
      matchPercentage: 72,
      verified: true,
      bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec.",
      liked: false,
    },
    {
      id: 4,
      image: user2.src,
      name: "Mads",
      age: 26,
      location: "Port Harcourt",
      matchPercentage: 77,
      verified: false,
      bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare eros mi, sed auctor libero finibus nec.",
      liked: false,
    },
    {
      id: 5,
      image: user2.src,
      name: "Love",
      age: 26,
      location: "Lagos",
      matchPercentage: 80,
      verified: true,
      bio: "Passionate about photography and design.",
      liked: false,
    },
    {
      id: 6,
      image: user2.src,
      name: "Kevin",
      age: 30,
      location: "PH",
      matchPercentage: 70,
      verified: false,
      bio: "No bio available",
      liked: false,
    },
    {
      id: 7,
      image: user2.src,
      name: "Lily",
      age: 26,
      location: "Lagos",
      matchPercentage: 89,
      verified: false,
      bio: "Traveler, writer, and coffee addict.",
      liked: false,
    },
    {
      id: 8,
      image: user2.src,
      name: "Jack",
      age: 30,
      location: "Lagos",
      matchPercentage: 87,
      verified: true,
      bio: "Tech entrepreneur and gamer.",
      liked: false,
    },
  ];
  

  